### ISSUE TITLE
Integration with Wazuh [Dashboard start not working]

### ISSUE THREAD

**Issue by myasn1k** [OwlH-net/OwlH-Node#48]
Hi, sorry bothering you another time.
I just installed Wazuh agent in an OwlH node as written [here](https://documentation.owlh.net/en/0.14.0/main/OwlHWazuh.html?highlight=wazuh).
I have a problem, i can't start Wazuh using the OwlH dashboard. Pressing on the "PLAY" button in the Wazuh section of the used node doesn't do nothing. 
I tried starting the agent manually and the Wazuh dashboard changed status from "OFF" to "ON", i can also stop Wazuh using the dashboard but i can't start it.
Am i missing something? Thanks a lot for the help!
PS: Everything is running under Docker.

Solved this problem i will try to integrate everything deeper using these two doc pages: 
- https://documentation.owlh.net/en/0.14.0/main/OwlH-elk.html
- https://documentation.owlh.net/en/0.14.0/main/OwlHBro.html?highlight=wazuh

**Comment by 72nomada** [comment]
Hi @myasn1k, thanks for your time trying it.

with Wazuh agent I have three questions for you, 
did you register agent into wazuh manager and got the agent key?
did you install the key in your wazuh agent? 
did you modify /var/ossec/etc/ossec.conf file to set the right manager server IP? 

Share the information and I will help you to end agent configuration. 

Thanks for your time

**Comment by myasn1k** [comment]
Thanks for the fast reply @jizquierdo-owlh ! 
- I used this method: https://documentation.wazuh.com/3.13/user-manual/registering/#registering-the-wazuh-agent-using-simple-registration-service
- No, i thought it was ok just using the method above (and it works, i mean i can see the Wazuh agent on the Manager, is it ok?)
- Yes, but i didn't use the IP, i used the Wazuh manager Docker hostname. Could it be a problem?

EDIT: "I tried starting the agent manually and the Wazuh dashboard changed status from "OFF" to "ON", i can also stop Wazuh using the dashboard but i can't start it."
It's not true, i also can't stop the wazuh agent from the dashboard

**Comment by 72nomada** [comment]
Hum, @myasn1k, if you can start and stop wazuh agent from the command line, we should be able to do from UI as well. 

Maybe you can update these lines on your conf/main.conf file: 
    "wazuhStop":{
        "stop":"/var/ossec/bin/ossec-control stop",
        "param":"-c",
        "command":"bash"
    },
    "wazuhStart":{
        "start":"/var/ossec/bin/ossec-control start",
        "param":"-c",
        "command":"bash"
    },

change them to: 

    "wazuhStop":{
        "stop":"systemctl stop wazuh-agent",
        "param":"-c",
        "command":"bash"
    },
    "wazuhStart":{
        "start":"systemctl start wazuh-agent",
        "param":"-c",
        "command":"bash"
    },

Let me know if this works

**Comment by 72nomada** [comment]
Hi @myasn1k, my fault, I've found the issue, is a bug in the node code, will update a new node version in a while. will notify you here.

**Comment by myasn1k** [comment]
> Hum, @myasn1k, if you can start and stop wazuh agent from the command line, we should be able to do from UI as well.
> 
> Maybe you can update these lines on your conf/main.conf file:
> "wazuhStop":{
> "stop":"/var/ossec/bin/ossec-control stop",
> "param":"-c",
> "command":"bash"
> },
> "wazuhStart":{
> "start":"/var/ossec/bin/ossec-control start",
> "param":"-c",
> "command":"bash"
> },
> 
> change them to:
> 
> ```
> "wazuhStop":{
>     "stop":"systemctl stop wazuh-agent",
>     "param":"-c",
>     "command":"bash"
> },
> "wazuhStart":{
>     "start":"systemctl start wazuh-agent",
>     "param":"-c",
>     "command":"bash"
> },
> ```
> 
> Let me know if this works

Sadly i'm running everything under Docker so systemd isn't a great option

> Hi @myasn1k, my fault, I've found the issue, is a bug in the node code, will update a new node version in a while. will notify you here.

Great! Thanks a lot!

**Comment by 72nomada** [comment]
Hi, @myasn1k we did release 0.16.0 this morning. the issue with Wazuh start/stop should be gone. Can you try and let us know?

**Comment by myasn1k** [comment]
Hi @jizquierdo-owlh 
Everything works fine now with Wazuh!

I found another (maybe) problem: configuring Zeek as done in this [video](https://www.youtube.com/watch?v=VXXXVZ2iQUQ) raises an "error" (i don't know if is supposed to work like this) that says "This node belongs to a cluster and is not the manager". Is it ok? Should i just run zeek as standalone and that's all?

Another question: how can i trigger an alert in OwlH that will be sent to Wazuh? I tried starting the STAP as done [here](https://github.com/OwlH-net/OwlH-Node/issues/47) and started surfing (pcaps files are generated succesfully) but i don't know if OwlH sends NIDS alerts to Wazuh. How can i test this? 

I can't understand also [this](https://documentation.owlh.net/en/0.14.0/main/OwlHBro.html?highlight=wazuh).
And i can't get [this](https://documentation.owlh.net/en/0.14.0/main/OwlH-elk.html) to work (kibana indexes are created but nothing shows up).

Thanks a lot for your help! Hoping not to bother you too much

**Comment by 72nomada** [comment]
Hi, 

Wazuh - great.

Zeek - This error means that your local system or the node IP is not the same IP on manager config, can you share your cluster config in your node? 

How can I trigger an alert in OwlH that will be sent to Wazuh? - Humm, well, Suricata and Zeek and owlh will create alerts, the analyzer will manage them. all of them are sent to /var/log/owlh/alerts.json by default. Wazuh must read this file to forward alerts to Manager/elk. By default analyzer is off, you may need to enable it UI -> nodes -> services configuration -> analyzer

About Zeek integration. we do enrich Zeek logs in two ways, export logs by default to json (Zeek doesn't do it by default) and we include a bro_engine field on some records to help Zeek events easily in ELK. 

About ELK. What issue do you have? 

If you don't mind we can close this related to wazuh and open as many as needed to address the other questions. also if you want we can have this discussion on slack channel https://bit.ly/2UWpAsa

Thanks a lot for your time and effort.

**Comment by myasn1k** [comment]
> If you don't mind we can close this related to wazuh and open as many as needed to address the other questions. also if you want we can have this discussion on slack channel https://bit.ly/2UWpAsa

Ok, I just joined the slack channel, i'll write here for the new questions.
Thanks!

**Comment by 72nomada** [comment]
cool thanks a lot
