### ISSUE TITLE
installing node issue

### ISSUE THREAD

**Issue by y0d4a** [OwlH-net/OwlH-Node#49]
Hi, i sucesfull installed master on new machine, and now want to install node on new machine also.
It is same OS image, but node cannot install, always get the error:

```
2020/08/27 13:45:06.889 [E]  Error downloading file: Get : unsupported protocol scheme ""
2020/08/27 13:45:06.889 [I]  Downloading  to
2020/08/27 13:45:06.889 [E]  Error Copying downloaded file: Get : unsupported protocol scheme ""
```

what is wrong?
i changed json conf. to node and install

**Comment by 72nomada** [comment]
Hi @y0d4a 

it seems a json config file format issue. did you use # to comment some lines? if so, please remove the line, do not comment it, json doesn't allow comments like this.
can you share/paste your config.json file? 

Thanks

**Comment by 72nomada** [comment]
maybe a "," in target field? 

if you are only going to install node you only need to set owlhnode:

original 

    "target": [
        "owlhmaster",
        "owlhnode",
        "owlhui"
    ],

yours should be something like this 

    "target": [
        "owlhnode"
    ],

**Comment by y0d4a** [comment]
yeah, i was thinking the same, but it is not, i removed 2 lines from target and changed action to install, here are those lines:

    "action": "install",
    "repourl":"http://repo.owlh.net/current-centos/",
    "target": [
        "owlhnode",
    ],

**Comment by y0d4a** [comment]
i found it, when i compare your and mine, i saw that there is , on node  :)

tnx.

**Comment by 72nomada** [comment]
Thanks @y0d4a
