### ISSUE TITLE
SURICATA - Alert if defined ruleset is not synchronized yet

### ISSUE THREAD

**Issue by 72nomada** [OwlH-net/OwlH-Node#60]
Alert when starting Suricata.
ask to sync before start Suricata

**Comment by sortiz1191** [comment]
![image.png](https://images.zenhubusercontent.com/5f2980436c83d247c928e37e/33f4c732-1e86-4709-a4e9-4727499cf4d6)

When ruleset for this suricata doesn't exists locally on node, disable stop/play button and show button for sync again ruleset.
