### ISSUE TITLE
Set log file rotation by default for main files. 

### ISSUE THREAD

**Issue by 72nomada** [OwlH-net/OwlH-Node#62]
Run verification on the analyzer, Suricata logs, and stats files rotation. 
Run it as owlh node start. if rotation is not set, set up it.

**Comment by sortiz1191** [comment]
- At UI, change max days by max files
- At UI, change file size from bytes to megas, gigas or teras (M, G, T)
- Add default files to rotate
      -/var/log/owlh/alerts.json
      -/var/log/suricata/suricata.log
      -/var/log/suricata/stats.log
      -/var/log/suricata/fast.log
      -/var/log/suricata/eve.json
